version: '3'

services:
    gmail_alert:
        build: .
        ports:
            - 5003:5003
        volumes:
            - .:/Lino-Alerta
        depends_on:
            - mongo_alert
        environment:
          - URI=//mongodb://ds041831.mlab.com:41831/api-alertas?authSource=api-alertas&w=1
          - CLIENT_ID=239258843822-cgk0toiq0bjuga3213t1qm0vhgh5gjh2.apps.googleusercontent.com
          - PROJECT_ID=lino-alerta-1537294243392
          - AUTH_URI=https://accounts.google.com/o/oauth2/auth
          - TOKEN_URI=https://www.googleapis.com/oauth2/v3/token
          - AUTH_PROVIDER=https://www.googleapis.com/oauth2/v1/certs
          - CLIENT_SECRET=zq6zFOwFxOnRJn8bekVfJv_7
          - REDIRECT_URIS_ZERO=["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
          - REDIRECT_URIS_ONE=["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]

    mongo_alert:
        image: mongo:latest
        command: mongod --port 27009
        ports:
            - 27009:27009
        volumes:
            - /l/mongo_alert/alert_db:/data/db
